2018-04-22 18:57 DEBUG    manager                       Figuring out config load paths
2018-04-22 18:57 DEBUG    manager                       Found config: /Users/eivindml/.flexget/config.yml
2018-04-22 18:57 DEBUG    manager                       Config file /Users/eivindml/.flexget/config.yml selected
2018-04-22 18:57 CRITICAL task          showrss.info    BUG: Unhandled error in plugin include: while scanning an alias\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 13\nexpected alphabetic or numeric character, but found '\n'\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 14
2018-04-22 18:57 CRITICAL manager       showrss.info    An unexpected crash has occurred. Writing crash report to /Users/eivindml/.flexget/crash_report.2018.04.22.185711140540.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.104
2018-04-22 18:57 WARNING  task          showrss.info    Aborting task (plugin: include)
2018-04-22 18:57 CRITICAL task          rarbg-alt       BUG: Unhandled error in plugin include: while scanning an alias\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 13\nexpected alphabetic or numeric character, but found '\n'\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 14
2018-04-22 18:57 CRITICAL manager       rarbg-alt       An unexpected crash has occurred. Writing crash report to /Users/eivindml/.flexget/crash_report.2018.04.22.185711160611.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.104
2018-04-22 18:57 WARNING  task          rarbg-alt       Aborting task (plugin: include)
2018-04-22 18:57 CRITICAL task          zooqle          BUG: Unhandled error in plugin include: while scanning an alias\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 13\nexpected alphabetic or numeric character, but found '\n'\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 14
2018-04-22 18:57 CRITICAL manager       zooqle          An unexpected crash has occurred. Writing crash report to /Users/eivindml/.flexget/crash_report.2018.04.22.185711178162.log. Please verify you are running the latest version of flexget by using "flexget -V" from CLI or by using version_checker plugin at http://flexget.com/wiki/Plugins/version_checker. You are currently using version 2.10.104
2018-04-22 18:57 WARNING  task          zooqle          Aborting task (plugin: include)
2018-04-22 18:57 CRITICAL task          norbits.net     BUG: Unhandled error in plugin include: while scanning an alias\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 13\nexpected alphabetic or numeric character, but found '\n'\n  in "/Users/eivindml/.flexget/series.yml", line 32, column 14
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/flexget/task.py", line 486, in __run_plugin
    return method(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flexget/event.py", line 23, in __call__
    return self.func(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/flexget/plugins/operate/include.py", line 46, in on_task_prepare
    include = yaml.load(inc_file)
  File "/Library/Python/2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Library/Python/2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Library/Python/2.7/site-packages/yaml/composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
  File "/Library/Python/2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Library/Python/2.7/site-packages/yaml/parser.py", line 379, in parse_block_sequence_first_entry
    return self.parse_block_sequence_entry()
  File "/Library/Python/2.7/site-packages/yaml/parser.py", line 384, in parse_block_sequence_entry
    if not self.check_token(BlockEntryToken, BlockEndToken):
  File "/Library/Python/2.7/site-packages/yaml/scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "/Library/Python/2.7/site-packages/yaml/scanner.py", line 224, in fetch_more_tokens
    return self.fetch_alias()
  File "/Library/Python/2.7/site-packages/yaml/scanner.py", line 607, in fetch_alias
    self.tokens.append(self.scan_anchor(AliasToken))
  File "/Library/Python/2.7/site-packages/yaml/scanner.py", line 926, in scan_anchor
    % ch.encode('utf-8'), self.get_mark())
ScannerError: while scanning an alias
  in "/Users/eivindml/.flexget/series.yml", line 32, column 13
expected alphabetic or numeric character, but found '\n'
  in "/Users/eivindml/.flexget/series.yml", line 32, column 14
